version: 2

build:
  image: latest

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - qt
        - all

formats: []
