version: 2

# Define standard job which can get run in different containers

jobs:

  py35_pyqt58:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            apt-get update
            apt-get install -y xvfb git \
                       python3 python3-dev python3-pip python3-wheel \
                       libgtk2.0-dev libgl1-mesa-glx libegl1-mesa libxrandr2 \
                       libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
            pip3 install fast-histogram
            python3 -c 'import fast_histogram'

workflows:
  version: 2
  build_and_test:
    jobs:
      - py35_pyqt58
