version: 2

jobs:
  main:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: |
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y xvfb python3 python3-setuptools python3-pytest python3-mock python3-pyqt5 python3-pyqt5.qtsvg python3-tk python3-dev python3-pip python3-wheel
      - run:
          name: Check Python, setuptools, and pip versions
          command: |
            python3 --version
            easy_install3 --version
            pip3 --version
      - run:
          name: Install glue and dependencies
          command: |
            pip3 install numpy
            pip3 install .[all]
      - run:
          name: Check dependency versions
          command: glue-deps list
      - run:
          name: Run tests
          command: |
            export DISPLAY=:99.0
            /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset
            export CIRCLECI=true
            python3 -c 'import glue; import sys; sys.exit(glue.test(no_optional_skip=True))'

workflows:
  version: 2
  build_and_test:
    jobs:
      - main
