version: 2

# Define standard job which can get run in different containers

jobs:

  py35_pyqt58:
    docker:
      - image: glueviz/py35-pyqt58:1.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            pip3 install fast-histogram
            python3 -c 'import fast_histogram'

workflows:
  version: 2
  build_and_test:
    jobs:
      - py35_pyqt58
