version: 2

# Define standard job which can get run in different containers

jobs:

  py35_pyqt58:
    docker:
      - image: glueviz/py35-pyqt58:1.1
    steps:
      - checkout
      - run:
          name: Start xvfb
          command: start-xvfb
      - run:
          name: Install virtualenv
          command: pip install virtualenv
      - run:
          name: Install missing dependencies
          command: |
            apt update
            apt install -y python-tk python3-tk graphviz
      - run:
          name: Run tests
          command: |
            virtualenv main --system-site-packages
            source main/bin/activate
            pip install pip --upgrade
            pip install fast-histogram
            python -c 'import fast_histogram'

workflows:
  version: 2
  build_and_test:
    jobs:
      - py35_pyqt58
