name: CI Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  linux:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      libraries: |
        apt:
          - libxkbcommon-x11-dev

      envs: |
        # Code style
        - linux: codestyle
          libraries:
          coverage: false

        # Standard tests
        # Linux builds - test on all supported PyQt5 and PySide2 versions,
        # and include all dependencies in some builds
        - linux: py37-test-pyqt510
        - linux: py37-test-pyqt511-all
        - linux: py37-test-pyqt512
        - linux: py37-test-pyqt513-all
        - linux: py37-test-pyside513-all
        - linux: py38-test-pyside514

        # Try out documentation build on Linux and macOS
        - linux: py37-docs-pyqt513
          coverage: false

  macos:
    # Windows failing erratically on GH actions without explanation
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      libraries: |
        brew:
          - enchant

      envs: |
        # Test a few configurations on MacOS X (Big Sur/Monterey on arm64 for py310)
        - macos: py37-test-pyqt513
        - macos: py38-test-pyqt514
        - macos: py310-test-pyqt515-all
          PLAT: arm64
        - macos: py38-test-pyside514

        # Try out documentation build on macOS
        - macos: py37-docs-pyqt513
          coverage: false

  windows:
    # Windows failing erratically on GH actions without explanation
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov

      envs: |
        - windows: py37-test-pyqt510
        # PyQt5.14 failed due to https://github.com/jupyter/qtconsole/issues/400 - fixed upstream
        - windows: py38-test-pyqt514-all
        - windows: py310-test-pyqt515
        - windows: py39-test-pyside515-all

        # Try out documentation build on Windows
        - windows: py38-docs-pyqt513
          coverage: false

  allowed_failures:
    # envs currently failing on GH actions; apt being unable to install the qt5 dependencies
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # The Linux PyQt 5.15 installation requires apt-getting its xcb deps and headless X11 display
      libraries: |
        apt:
          - libqt5gui5
          - libxkbcommon-x11-dev
          - libxcb-xinerama0-dev
          - libx11-xcb-dev

      envs: |
        - linux: py39-test-pyqt515
        - linux: py310-test-pyside515-all

        # Test against latest developer versions of some packages
        - linux: py310-test-pyqt515-dev-all
