name: CI Workflows

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  initial_checks:
    # Mandatory checks before CI tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # The Linux PyQt 5.15 installation requires apt-getting its xcb deps and headless X11 display
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
        brew:
          - enchant

      envs: |
        # Standard tests
        # Linux builds - test on all supported PyQt5 and PySide2 versions,
        # and include all dependencies in some builds
        - linux: py38-test-pyqt514-all
        - linux: py38-test-pyside514
        - linux: py39-test-pyqt515
        - linux: py39-test-pyside515

        # Documentation build
        - linux: py38-docs-pyqt514
          coverage: false
        - macos: py39-docs-pyqt515
          coverage: false
        - windows: py310-docs-pyqt63
          coverage: false

        # Test a few configurations on MacOS X
        - macos: py38-test-pyqt514-all
        - macos: py310-test-pyqt515

        # Test some configurations on Windows
        - windows: py38-test-pyqt514
        - windows: py310-test-pyqt515-all

  allowed_failures:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # Linux PyQt 5.15 and 6.3 installations require apt-getting xcb and EGL deps
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1-mesa
        brew:
          - enchant
      envs: |
        # Some (PySide2 in particular) envs are failing with runtime errors;
        # PyQt6 and PySide6 support in progress
        - linux: py310-test-pyside63
        - linux: py310-test-pyqt63-all
        - linux: py310-test-pyside64
        - linux: py310-test-pyqt64-all

        - macos: py310-test-pyside63
        - macos: py310-test-pyqt64

        - windows: py310-test-pyqt63
        - windows: py310-test-pyside64

        # Test against latest developer versions of some packages
        - linux: py310-test-pyqt515-dev-all

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      # Setup PyQt5 deps and headless X server as per pyvista/setup-headless-display-action@v1
      libraries: '^libxcb.*-dev libxkbcommon-x11-dev libgl1-mesa-glx xvfb'
      test_extras: 'test,qt'
      test_command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & sleep 3; DISPLAY=:99.0 pytest --pyargs glue
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
