name: CI Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  initial_checks:
    # Mandatory checks before CI tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: false
      envs: |
        # Code style
        - linux: codestyle

  tests:
    needs: initial_checks
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      coverage: codecov
      display: true
      # Linux PyQt 5.15 and 6.x installations require apt-getting xcb and EGL deps
      # and headless X11 display; as of Python 3.11 Scipy and h5py also need their own deps.
      libraries: |
        apt:
          - '^libxcb.*-dev'
          - libxkbcommon-x11-dev
          - libegl1-mesa
          - libopenblas-dev
          - libhdf5-dev
        brew:
          - enchant

      envs: |
        # Standard tests
        # Linux builds - test on all supported PyQt5/6 and PySide2/6 versions,
        # and include all dependencies in some builds
        - linux: py39-test-pyqt515-dev
        - linux: py311-test-pyqt514-dev

        # Documentation build
        - linux: py38-docs-pyqt514
          coverage: false

        # Test a few configurations on macOS
        - macos: py310-test-pyqt515-dev
        - macos: py311-test-pyqt64-dev

        # Test some configurations on Windows
        - windows: py39-test-pyqt514-dev
        - windows: py310-test-pyqt63-dev

        # Test against latest developer versions of some packages
        - linux: py310-test-pyqt515-dev-all
        - linux: py311-test-pyqt64-dev

  publish:
    needs: tests
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      # Setup PyQt5 deps and headless X server as per pyvista/setup-headless-display-action@v1
      libraries: '^libxcb.*-dev libxkbcommon-x11-dev libgl1-mesa-glx libopenblas-dev libhdf5-dev xvfb'
      test_extras: 'test,qt'
      test_command: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & sleep 3; DISPLAY=:99.0 pytest --pyargs glue
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
